// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBgczMsZYrnbM2IdOrfQOeQ3qKFo34px8',
    appId: '1:408344046428:web:4eba6dd42b6a9339ef6f99',
    messagingSenderId: '408344046428',
    projectId: 't-store-b6075',
    authDomain: 't-store-b6075.firebaseapp.com',
    storageBucket: 't-store-b6075.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8-H64ITOUCFI9_3iA0Z7ua7arKJko4rg',
    appId: '1:408344046428:android:67c8cc6abf068278ef6f99',
    messagingSenderId: '408344046428',
    projectId: 't-store-b6075',
    storageBucket: 't-store-b6075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2v9f4e9gdaB7Xm1cGtCU3b-D56bCtL_w',
    appId: '1:408344046428:ios:81bed8634a49d9ecef6f99',
    messagingSenderId: '408344046428',
    projectId: 't-store-b6075',
    storageBucket: 't-store-b6075.appspot.com',
    iosClientId: '408344046428-uv1abbs1gtsurs4jff20oht24tqa0mca.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2v9f4e9gdaB7Xm1cGtCU3b-D56bCtL_w',
    appId: '1:408344046428:ios:81bed8634a49d9ecef6f99',
    messagingSenderId: '408344046428',
    projectId: 't-store-b6075',
    storageBucket: 't-store-b6075.appspot.com',
    iosClientId: '408344046428-uv1abbs1gtsurs4jff20oht24tqa0mca.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBgczMsZYrnbM2IdOrfQOeQ3qKFo34px8',
    appId: '1:408344046428:web:af33740e697de235ef6f99',
    messagingSenderId: '408344046428',
    projectId: 't-store-b6075',
    authDomain: 't-store-b6075.firebaseapp.com',
    storageBucket: 't-store-b6075.appspot.com',
  );

}